name: Second Implementation

on:
  workflow_call:
    inputs:
      hml:
        required: true
        type: string
        description: 'Choose HML Environments'
      hml_1-5:
        required: true
        type: string
        description: 'Choose HML Environments'

jobs:

  deploy-hml:
    name: Deploy to hml
    if: "inputs.hml == 'true' && (inputs.hml_1-5 == 'false' || inputs.hml_1-5 == 'true') && (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')"
    #if: "inputs.hml == 'true' && (inputs.hml_1-5 == 'false' || inputs.hml_1-5 == 'true')"
    runs-on: ubuntu-latest
    environment:
      name: hml
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to HML
      run: echo "Deploying to HML"
      env:
        RESULT: success

    - uses: actions/checkout@v4
      name: Checkout scripts
      with:
         repository: Ll2223/ga-pipelines
         token: ${{ secrets.GH_TOKEN }}
         path: templates
         sparse-checkout: scripts/PipelineRundeck
    
    - name: Get changed YAML files
      id: yaml-files
      run: |
        pip install requests
        export GH_TOKEN=${{ secrets.GH_TOKEN }}
        files=$(python templates/scripts/PipelineRundeck/identify-yaml.py)
        echo "::set-output name=files::${files}"

    - name: Staging Environment Variables
      id: staging-env-vars
      uses: raven-actions/environment-variables@v1.0.0
      with:
        github-token: ${{ secrets.TESTE_TOKEN }}
        environment: hml

    - name: Replace with envsubst
      id: replace-with-envsubst
      run: |
        IFS=',' read -ra yaml_files <<< "${{ steps.yaml-files.outputs.files }}"
        for file in "${yaml_files[@]}"; do
          envsubst < "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          echo "$file" >> modified_files.txt
        done
        echo "::set-output name=modified_files::${yaml_files[*]}"
        echo "::set-output name=modified_files_path::modified_files.txt"

    - name: Show modified files
      run: cat modified_files.txt

    - name: Grant execute permissions to post-rundeck.sh
      run: chmod +x templates/scripts/PipelineRundeck/post-rundeck.sh

    # - name: Post Job to Rundeck
    #   run: bash templates/scripts/PipelineRundeck/post-rundeck.sh
    #   env:
    #     RUNDECK_TOKEN: ${{ secrets.RUNDECK_TOKEN }}
    #     HOST: ${{ secrets.RUNDECK_HOST }}
  
  deploy-hml_1-5:
    name: Deploy to hml 1-5
    strategy:
      matrix:
        environment: ["HML-1", "HML-5"]
    if: "inputs.hml_1-5 == 'true' && (inputs.hml == 'false' || inputs.hml == 'true') && (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')"
    #if: "(inputs.hml_1-5 == 'true' && inputs.hml == 'false') || (inputs.hml_1-5 == 'true' && inputs.hml == 'true')"
    needs: [deploy-hml]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to HML
      run: echo "Deploying to HML"
      env:
        RESULT: success

    - uses: actions/checkout@v4
      name: Checkout scripts
      with:
         repository: Ll2223/ga-pipelines
         token: ${{ secrets.GH_TOKEN }}
         path: templates
         sparse-checkout: scripts/PipelineRundeck
    
    - name: Get changed YAML files
      id: yaml-files
      run: |
        pip install requests
        export GH_TOKEN=${{ secrets.GH_TOKEN }}
        files=$(python templates/scripts/PipelineRundeck/identify-yaml.py)
        echo "::set-output name=files::${files}"

    - name: Staging Environment Variables
      id: staging-env-vars
      uses: raven-actions/environment-variables@v1.0.0
      with:
        github-token: ${{ secrets.TESTE_TOKEN }}
        environment: ${{ matrix.environment }}

    - name: Replace with envsubst
      id: replace-with-envsubst
      run: |
        IFS=',' read -ra yaml_files <<< "${{ steps.yaml-files.outputs.files }}"
        for file in "${yaml_files[@]}"; do
          envsubst < "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          echo "$file" >> modified_files.txt
        done
        echo "::set-output name=modified_files::${yaml_files[*]}"
        echo "::set-output name=modified_files_path::modified_files.txt"

    - name: Show modified files
      run: cat modified_files.txt

    - name: Grant execute permissions to post-rundeck.sh
      run: chmod +x templates/scripts/PipelineRundeck/post-rundeck.sh

    # - name: Post Job to Rundeck
    #   run: bash templates/scripts/PipelineRundeck/post-rundeck.sh
    #   env:
    #     RUNDECK_TOKEN: ${{ secrets.RUNDECK_TOKEN }}
    #     HOST: ${{ secrets.RUNDECK_HOST }}

  deploy-prd:
    name: Deploy to prd
    needs: [deploy-hml, deploy-hml_1-5]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    #if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    runs-on: ubuntu-latest
    environment:
      name: prd
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
      name: Checkout scripts
      with:
         repository: Ll2223/ga-pipelines
         token: ${{ secrets.GH_TOKEN }}
         path: templates
         sparse-checkout: scripts/PipelineRundeck
    
    - name: Get changed YAML files
      id: yaml-files
      run: |
        pip install requests
        export GH_TOKEN=${{ secrets.GH_TOKEN }}
        files=$(python templates/scripts/PipelineRundeck/identify-yaml.py)
        echo "::set-output name=files::${files}"

    - name: Staging Environment Variables
      id: staging-env-vars
      uses: raven-actions/environment-variables@v1.0.0
      with:
        github-token: ${{ secrets.TESTE_TOKEN }}
        environment: prd

    - name: Replace with envsubst
      run: |
        IFS=',' read -ra yaml_files <<< "${{ steps.yaml-files.outputs.files }}"
        for file in "${yaml_files[@]}"; do
          envsubst < $file | tee $file
        done
